@ServerURL = http://localhost:8080
@Authorization = Bearer {{ServieToken}} 
@UserToken = Bearer {{Token}}

@ServieToken = d463d1ac-91d3-4ac1-8dc3-85b2efc3c4b1
@Token = 362224b32f8e43c6b51189a30ce452f7

POST {{ServerURL}}/api/account/login
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id":"service",
    "username":"serviceadmin@email.com",
    "password":"KoEEBfC/kRLCMfXUrtI/3TlMlJLouQYf2rop1vCuNTY=",
    "grant_type":"password",
    "scope":"",
    "client_secret":"secret"
}

###

POST {{ServerURL}}/api/account/login
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id":"webuser",
    "username":"kunanon3",
    "password":"lamysri3",
    "grant_type":"password",
    "scope":"",
    "client_secret":"secret"
}

###

Post {{ServerURL}}/api/account/userinfo
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id":"webuser",
    "user_token":"{{UserToken}}"
}
###
Post {{ServerURL}}/api/account/refresh_token
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id":"webuser",
    "user_token":"{{UserToken}}"
}

###
Post {{ServerURL}}/api/account/create_user
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id": "aaa",
    "email":"cop30@email.com",
    "username":"kunanon30",
    "password":"lamysri30",
    "firstname":"kunanon30",
    "lastname":"lamysri30",
    "role":"\"webuser\"",
    "status" : "ACTIVE",
    "otp_status": null,
    "pin" : null,
    "user_id" : "cop10",
    "mobile_no" : "0909090909",
    "mobile_country_code" : "66",
    "citizen_id" : "1100101010101",
    "passport_no" : null,
    "id_type" : "citizen_id",
    "date_of_birth" : "1994-07-13"
}

###
Post {{ServerURL}}/api/account/create_user
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id": "webuser",
    "email":"cop5@email.com",
    "username":"kunanon5",
    "password":"lamysri5",
    "firstname":"kunanon5",
    "lastname":"lamysri5",
    "role":"\"webuser\"",
    "status" : "ACTIVE",
    "otp_status": null,
    "pin" : null,
    "user_id" : "cop5",
    "mobile_no" : "5555555555",
    "mobile_country_code" : "66",
    "citizen_id" : "5555555555",
    "passport_no" : null,
    "id_type" : "citizen_id",
    "date_of_birth" : "1994-09-13"
}

###

Post {{ServerURL}}/api/account/update_user/cop10
Authorization: {{Authorization}}
Content-Type: application/json

{

    "client_id": "webuser",
	"email":null,
	"username":null,
	"password":null,
	"firstname":"kunanonChange100",
	"lastname":"lamysriChange100",
	"role":"\"webuser\"",
    "status" : null,
    "otp_status": null,
    "pin" : null,
    "user_id" : null,
    "mobile_no" : null,
    "mobile_country_code" : null,
    "citizen_id" : null,
    "passport_no" : null,
    "id_type" : null,
    "date_of_birth" : null

}
###

Post {{ServerURL}}/api/account/set_password/cop20
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id": "service",
    "password" : "lamysri100settpassword"
}

###

Post {{ServerURL}}/api/account/delete_user/cop10
Authorization: {{Authorization}}
Content-Type: application/json

{
    "client_id": "service"
}

###

Post {{ServerURL}}/api/account/list_userinfo
Authorization: {{Authorization}}
Content-Type: application/json

{

    "client_id":"webuser",
	"username": "kunanon30", 
	"user_id":null, 
	"firstname": null, 
	"lastname":null, 
	"cif_no" : null, 
	"id_no":null, 
	"mobile_no":null, 
	"email":null, 
	"register_date_from" :null, 
	"register_date_to" : null, 
	"status": null, 
	"otp_status" : null,
    "pin_status" : null,
    "page":1,
    "row_per_page":0,
    "include_delete":true



}